--Find out list of high_value_clients we have in each country
--Individuals with an excelent credit score and have an income of above $100K and an account balance of above $50K


customerid | surname     | credit_score | estimated_salary | balance       | country
------------------------------------------------------------------------------
1          | Paterson    | 850          | 184044.8         | 108508.82     | Germany
2          | Kambinachi  | 850          | 109089.04        | 114347.85     | Spain
3          | Johnson     | 850          | 175853.64        | 97408.03      | Spain
4          | Welch       | 850          | 140075.55        | 54901.01      | Germany
5          | Maslova     | 850          | 103902.11        | 146343.98     | Spain
6          | Ward        | 850          | 186335.07        | 169445.4      | France
7          | Yao         | 850          | 162087.82        | 115378.94     | Spain
8          | Theus       | 850          | 162149.07        | 91292.7       | Spain
9          | Jamieson    | 850          | 136539.13        | 100476.46     | Spain
10         | Elliott     | 850          | 163989.66        | 99816.46      | France
--There are 964 others
